package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"fmt"

	"github.com/dugtriol/BarterApp/internal/controller/graph/model"
)

// NewProduct is the resolver for the newProduct field.
func (r *subscriptionResolver) NewProduct(ctx context.Context, category *model.ProductCategory) (
	<-chan *model.Product, error,
) {
	panic(fmt.Errorf("not implemented: NewProduct - newProduct"))
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
