package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"fmt"

	"github.com/dugtriol/BarterApp/internal/controller"
	"github.com/dugtriol/BarterApp/internal/controller/graph/model"
	"github.com/dugtriol/BarterApp/internal/service"
	"github.com/dugtriol/BarterApp/pkg/hasher"
	"github.com/dugtriol/BarterApp/pkg/middleware"
)

// Create is the resolver for the Create field.
func (r *mutationResolver) Register(ctx context.Context, input *model.CreateUserInput) (*model.AuthResponse, error) {
	_, err := r.Services.Auth.GetByEmail(ctx, r.Log, service.UserGetByEmailInput{Email: input.Email})
	if err == nil {
		r.Log.Error("Resolvers.Create - r.Services.Auth.GetByEmail: email already exists")
		return nil, controller.ErrAlreadyExists
	}
	output, err := r.Services.Auth.Register(
		ctx, service.AuthRegisterInput{
			Name:     input.Name,
			Email:    input.Email,
			Phone:    input.Phone,
			Password: input.Password,
			City:     input.City,
			Mode:     input.Mode.String(),
		},
	)
	if err != nil {
		r.Log.Error("Resolvers.Create - r.Services.Auth.Register: ", err)
		return nil, err
	}

	authToken, err := r.Services.Auth.GenToken(output.Id)
	if err != nil {
		r.Log.Error("Resolvers.Create - r.Services.Auth.GenerateToken: ", err)
		return nil, err
	}

	var mode model.UserMode
	err = mode.UnmarshalGQL(output.Mode)
	if err != nil {
		r.Log.Error("Resolvers.User -  mode.UnmarshalGQL(output.Mode): ", err)
		return nil, controller.ErrNotValid
	}

	result := model.User{
		ID:       output.Id,
		Name:     output.Name,
		Password: output.Password,
		Email:    output.Email,
		Phone:    output.Phone,
		City:     output.City,
		Mode:     mode,
	}

	response := model.AuthResponse{
		AuthToken: authToken,
		User:      &result,
	}
	return &response, nil
}

// TotalUsers is the resolver for the totalUsers field.
func (r *queryResolver) TotalUsers(ctx context.Context) (int, error) {
	return 1, nil
}

// AllUsers is the resolver for the allUsers field.
func (r *queryResolver) AllUsers(ctx context.Context) ([]*model.User, error) {
	return nil, nil
}

// TotalProducts is the resolver for the totalProducts field.
func (r *queryResolver) TotalProducts(ctx context.Context) (int, error) {
	panic(fmt.Errorf("not implemented: TotalProducts - totalProducts"))
}

// AllProducts is the resolver for the allProducts field.
func (r *queryResolver) AllProducts(
	ctx context.Context, category *model.ProductCategory, first *int, start *int,
) ([]*model.Product, error) {
	panic(fmt.Errorf("not implemented: AllProducts - allProducts"))
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	output, err := r.Services.Auth.GetById(ctx, r.Log, service.UserGetByIdInput{Id: id})
	if err != nil {
		r.Log.Error("Resolvers.User -  r.Services.Auth.GetById: ", err)
		return nil, controller.ErrNotFound
	}

	var mode model.UserMode
	err = mode.UnmarshalGQL(output.Mode)
	if err != nil {
		r.Log.Error("Resolvers.User -  mode.UnmarshalGQL(output.Mode): ", err)
		return nil, controller.ErrNotValid
	}

	result := model.User{
		ID:       output.Id,
		Name:     output.Name,
		Password: output.Password,
		Email:    output.Email,
		Phone:    output.Phone,
		City:     output.City,
		Mode:     mode,
	}
	return &result, nil
}

// Product is the resolver for the Product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	product, err := r.Services.Product.GetById(ctx, r.Log, service.GetByIdProductInput{Id: id})
	if err != nil {
		r.Log.Error("Resolvers.Product -  r.Services.Product.GetById: ", err)
		return nil, controller.ErrNotFound
	}

	var category model.ProductCategory
	err = category.UnmarshalGQL(product.Category)
	if err != nil {
		r.Log.Error("Resolvers.Product -  category.UnmarshalGQL(product.Category): ", err)
		return nil, controller.ErrNotValid
	}

	var status model.ProductStatus
	err = status.UnmarshalGQL(product.Status)
	if err != nil {
		r.Log.Error("Resolvers.Product -  status.UnmarshalGQL(product.Status): ", err)
		return nil, controller.ErrNotValid
	}

	result := model.Product{
		ID:          product.Id,
		Category:    category,
		Name:        product.Name,
		Description: product.Description,
		Image:       product.Image,
		Status:      status,
		CreatedAt:   product.CreatedAt.String(),
	}
	return &result, nil

}

// NewProduct is the resolver for the newProduct field.
func (r *subscriptionResolver) NewProduct(ctx context.Context, category *model.ProductCategory) (
	<-chan *model.Product, error,
) {
	panic(fmt.Errorf("not implemented: NewProduct - newProduct"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }

func (r *mutationResolver) Login(ctx context.Context, input *model.LoginInput) (*model.AuthResponse, error) {
	output, err := r.Services.Auth.GetByEmail(ctx, r.Log, service.UserGetByEmailInput{Email: input.Email})
	if err != nil {
		r.Log.Error("Resolvers.Login - r.Services.Auth.GetByEmail: ", err)
		return nil, controller.ErrAlreadyExists
	}
	err = hasher.CheckPassword(input.Password, output.Password)
	if err != nil {
		r.Log.Error("Resolvers.Login - hasher.CheckPassword: ", err)
		return nil, controller.ErrInvalidPassword
	}

	authToken, err := r.Services.Auth.GenToken(output.Id)
	if err != nil {
		r.Log.Error("Resolvers.Create - r.Services.Auth.GenerateToken: ", err)
		return nil, controller.ErrNotValid
	}

	var mode model.UserMode
	err = mode.UnmarshalGQL(output.Mode)
	if err != nil {
		r.Log.Error("Resolvers.User -  mode.UnmarshalGQL(output.Mode): ", err)
		return nil, controller.ErrNotValid
	}

	result := model.User{
		ID:       output.Id,
		Name:     output.Name,
		Password: output.Password,
		Email:    output.Email,
		Phone:    output.Phone,
		City:     output.City,
		Mode:     mode,
	}

	response := model.AuthResponse{
		AuthToken: authToken,
		User:      &result,
	}
	return &response, nil
}

func (r *mutationResolver) CreateProduct(ctx context.Context, input *model.CreateProductInput) (*model.Product, error) {
	currentUser, err := middleware.GetCurrentUserFromCTX(ctx)
	if err != nil {
		r.Log.Error("Resolvers.Product -  middleware.GetCurrentUserFromCTX: no user in context")
		return nil, controller.ErrNotAuthenticated
	}
	product, err := r.Services.Product.Create(
		ctx, service.CreateProductInput{
			Category:    input.Category.String(),
			Name:        input.Name,
			Description: input.Description,
			Image:       input.Image,
			UserId:      currentUser.Id,
		},
	)
	if err != nil {
		r.Log.Error("Resolvers.Product -  r.Services.Product.Create: ", err)
		return nil, controller.ErrNotCreated
	}
	var category model.ProductCategory
	err = category.UnmarshalGQL(product.Category)
	if err != nil {
		r.Log.Error("Resolvers.Product -  category.UnmarshalGQL(product.Category): ", err)
		return nil, controller.ErrNotValid
	}

	var status model.ProductStatus
	err = status.UnmarshalGQL(product.Status)
	if err != nil {
		r.Log.Error("Resolvers.Product -  status.UnmarshalGQL(product.Status): ", err)
		return nil, controller.ErrNotValid
	}

	result := model.Product{
		ID:          product.Id,
		Category:    category,
		Name:        product.Name,
		Description: product.Description,
		Image:       product.Image,
		Status:      status,
		CreatedAt:   product.CreatedAt.String(),
	}
	return &result, nil
}

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
