BEGIN;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS user_mode CASCADE;
DROP TABLE IF EXISTS products;
DROP TYPE IF EXISTS product_category CASCADE;
DROP TYPE IF EXISTS product_status CASCADE;
COMMIT;