package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/dugtriol/BarterApp/graph/model"
	"github.com/dugtriol/BarterApp/internal/controller"
	"github.com/dugtriol/BarterApp/internal/entity"
	"github.com/dugtriol/BarterApp/internal/service"
	"github.com/dugtriol/BarterApp/pkg/hasher"
	"github.com/dugtriol/BarterApp/pkg/middleware"
)

// Register is the resolver for the Register field.
func (r *mutationResolver) Register(ctx context.Context, input *model.CreateUserInput) (*model.AuthResponse, error) {
	isValid := validation(ctx, input)
	if !isValid {
		return nil, controller.ErrInput
	}

	_, err := r.Services.User.GetByEmail(ctx, r.Log, service.UserGetByEmailInput{Email: input.Email})
	if err == nil {
		r.Log.Error("Resolvers.Create - r.Services.User.GetByEmail: email already exists")
		return nil, controller.ErrAlreadyExists
	}
	output, err := r.Services.User.Register(
		ctx, service.AuthRegisterInput{
			Name:     input.Name,
			Email:    input.Email,
			Phone:    input.Phone,
			Password: input.Password,
			City:     input.City,
			Mode:     input.Mode.String(),
		},
	)
	if err != nil {
		r.Log.Error("Resolvers.Create - r.Services.User.Register: ", err)
		return nil, err
	}

	authToken, err := r.Services.User.GenToken(output.Id)
	if err != nil {
		r.Log.Error("Resolvers.Create - r.Services.User.GenerateToken: ", err)
		return nil, err
	}

	var mode model.UserMode
	err = mode.UnmarshalGQL(output.Mode)
	if err != nil {
		r.Log.Error("Resolvers.User -  mode.UnmarshalGQL(output.Mode): ", err)
		return nil, controller.ErrNotValid
	}

	result := model.User{
		ID:       output.Id,
		Name:     output.Name,
		Password: output.Password,
		Email:    output.Email,
		Phone:    output.Phone,
		City:     output.City,
		Mode:     mode,
	}

	response := model.AuthResponse{
		AuthToken: authToken,
		User:      &result,
	}
	return &response, nil
}

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input *model.LoginInput) (*model.AuthResponse, error) {
	isValid := validation(ctx, input)
	if !isValid {
		return nil, controller.ErrInput
	}

	output, err := r.Services.User.GetByEmail(ctx, r.Log, service.UserGetByEmailInput{Email: input.Email})
	if err != nil {
		r.Log.Error("Resolvers.Login - r.Services.User.GetByEmail: ", err)
		return nil, controller.ErrAlreadyExists
	}
	err = hasher.CheckPassword(input.Password, output.Password)
	if err != nil {
		r.Log.Error("Resolvers.Login - hasher.CheckPassword: ", err)
		return nil, controller.ErrInvalidPassword
	}

	authToken, err := r.Services.User.GenToken(output.Id)
	if err != nil {
		r.Log.Error("Resolvers.Create - r.Services.User.GenerateToken: ", err)
		return nil, controller.ErrNotValid
	}

	var mode model.UserMode
	err = mode.UnmarshalGQL(output.Mode)
	if err != nil {
		r.Log.Error("Resolvers.User -  mode.UnmarshalGQL(output.Mode): ", err)
		return nil, controller.ErrNotValid
	}

	result := model.User{
		ID:       output.Id,
		Name:     output.Name,
		Password: output.Password,
		Email:    output.Email,
		Phone:    output.Phone,
		City:     output.City,
		Mode:     mode,
	}

	response := model.AuthResponse{
		AuthToken: authToken,
		User:      &result,
	}
	return &response, nil
}

// CreateProduct is the resolver for the CreateProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input *model.CreateProductInput) (*model.Product, error) {
	currentUser, err := middleware.GetCurrentUserFromCTX(ctx)
	if err != nil {
		r.Log.Error("Resolvers.Product -  middleware.GetCurrentUserFromCTX: no user in context")
		return nil, controller.ErrNotAuthenticated
	}
	product, err := r.Services.Product.Create(
		ctx, service.CreateProductInput{
			Category:    input.Category.String(),
			Name:        input.Name,
			Description: input.Description,
			Image:       input.Image,
			UserId:      currentUser.Id,
		},
	)
	if err != nil {
		r.Log.Error("Resolvers.Product -  r.Services.Product.Create: ", err)
		return nil, controller.ErrNotCreated
	}

	var category model.ProductCategory
	err = category.UnmarshalGQL(product.Category)
	if err != nil {
		r.Log.Error("Resolvers.Product -  category.UnmarshalGQL(product.Category): ", err)
		return nil, controller.ErrNotValid
	}

	var status model.ProductStatus
	err = status.UnmarshalGQL(product.Status)
	if err != nil {
		r.Log.Error("Resolvers.Product -  category.UnmarshalGQL(product.Status): ", err)
		return nil, controller.ErrNotValid
	}

	result := model.Product{
		ID:          product.Id,
		Category:    category,
		Name:        product.Name,
		Description: product.Description,
		Image:       product.Image,
		Status:      status,
		CreatedAt:   product.CreatedAt.String(),
		CreatedBy:   product.UserId,
	}
	return &result, nil
}

// Like is the resolver for the Like field.
func (r *mutationResolver) Like(ctx context.Context, productID string) (string, error) {
	currentUser, err := middleware.GetCurrentUserFromCTX(ctx)
	if err != nil {
		r.Log.Error("Resolvers.Product -  middleware.GetCurrentUserFromCTX: no user in context")
		return "", controller.ErrNotAuthenticated
	}

	id, err := r.Services.Favorites.Add(
		ctx, entity.Favorites{
			UserId:    currentUser.Id,
			ProductId: productID,
		},
	)
	if err != nil {
		r.Log.Error("Resolvers.Product -  r.Services.Favorites.Add")
		return "", controller.ErrNotValid
	}

	return id, nil
}

// Unlike is the resolver for the Unlike field.
func (r *mutationResolver) Unlike(ctx context.Context, productID string) (bool, error) {
	currentUser, err := middleware.GetCurrentUserFromCTX(ctx)
	if err != nil {
		r.Log.Error("Resolvers.Product -  middleware.GetCurrentUserFromCTX: no user in context")
		return false, controller.ErrNotAuthenticated
	}

	ok, err := r.Services.Favorites.Delete(
		ctx, entity.Favorites{
			UserId:    currentUser.Id,
			ProductId: productID,
		},
	)
	if err != nil {
		r.Log.Error("Resolvers.Product -  r.Services.Favorites.Add")
		return ok, controller.ErrNotValid
	}

	return ok, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
