package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/dugtriol/BarterApp/graph/model"
)

// PostedProducts is the resolver for the postedProducts field.
func (r *userResolver) PostedProducts(ctx context.Context, obj *model.User) ([]*model.Product, error) {
	limit := 100
	offset := 0
	output, err := r.Services.Product.GetByUserId(ctx, limit, offset, obj.ID)
	if err != nil {
		r.Log.Error("userResolver - PostedProducts - r.Services.Product.GetByUserId: ", err)
		return nil, err
	}
	return output, nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
