env: "local" # local, dev, prod
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "test"
  password: "test"
database_data:
  host: "localhost"
  port: 5432
  user: "test"
  password: "test"
  dbname: "barterDB"
email_data:
  EMAIL_SENDER_NAME: "barterapp"
  EMAIL_SENDER_ADDRESS: "barterappproject@gmail.com"
  EMAIL_SENDER_PASSWORD: "fvxy nozn xvwg rbah"